import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const pdfStyles = StyleSheet.create({
    page: { fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a', backgroundColor: 'white' },
    header: { backgroundColor: '#15803d', color: 'white', padding: '20 30' },
    headerName: { fontSize: 20, fontWeight: 'bold', marginBottom: 6 },
    headerContact: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, fontSize: 9, opacity: 0.9 },
    body: { padding: '20 30' },
    section: { marginBottom: 14 },
    sectionTitle: { fontSize: 8, fontWeight: 'bold', color: '#15803d', textTransform: 'uppercase', letterSpacing: 1.5, borderBottomWidth: 1, borderBottomColor: '#bbf7d0', paddingBottom: 3, marginBottom: 8 },
    text: { fontSize: 10, lineHeight: 1.6, color: '#374151' },
    skillsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
    skillTag: { backgroundColor: '#f0fdf4', border: '1 solid #86efac', color: '#166534', fontSize: 8, padding: '3 8', borderRadius: 10 },
    twoCol: { flexDirection: 'row', gap: 20 },
    col: { flex: 1 },
    footer: { textAlign: 'center', fontSize: 8, color: '#9ca3af', borderTopWidth: 1, borderTopColor: '#e5e7eb', padding: '10 0', marginTop: 10 }
})

const ResumePDF = ({ data }) => {
    const skills = data.skills ? data.skills.split(',').map(s => s.trim()).filter(Boolean) : []
    const languages = data.languages ? data.languages.split(',').map(l => l.trim()).filter(Boolean) : []

    return (
        <Document>
            <Page size='A4' style={pdfStyles.page}>
                <View style={pdfStyles.header}>
                    <Text style={pdfStyles.headerName}>{data.fullName || 'Your Name'}</Text>
                    <View style={pdfStyles.headerContact}>
                        {data.email && <Text>Email: {data.email}</Text>}
                        {data.phone && <Text>Phone: {data.phone}</Text>}
                        {data.location && <Text>Location: {data.location}</Text>}
                        {data.linkedin && <Text>LinkedIn: {data.linkedin}</Text>}
                        {data.website && <Text>Web: {data.website}</Text>}
                    </View>
                </View>
                <View style={pdfStyles.body}>
                    {data.summary && (
                        <View style={pdfStyles.section}>
                            <Text style={pdfStyles.sectionTitle}>Professional Summary</Text>
                            <Text style={pdfStyles.text}>{data.summary}</Text>
                        </View>
                    )}
                    {data.experience && (
                        <View style={pdfStyles.section}>
                            <Text style={pdfStyles.sectionTitle}>Work Experience</Text>
                            <Text style={pdfStyles.text}>{data.experience}</Text>
                        </View>
                    )}
                    {data.education && (
                        <View style={pdfStyles.section}>
                            <Text style={pdfStyles.sectionTitle}>Education</Text>
                            <Text style={pdfStyles.text}>{data.education}</Text>
                        </View>
                    )}
                    <View style={pdfStyles.twoCol}>
                        {skills.length > 0 && (
                            <View style={pdfStyles.col}>
                                <Text style={pdfStyles.sectionTitle}>Skills</Text>
                                <View style={pdfStyles.skillsRow}>
                                    {skills.map((s, i) => <Text key={i} style={pdfStyles.skillTag}>{s}</Text>)}
                                </View>
                            </View>
                        )}
                        {languages.length > 0 && (
                            <View style={pdfStyles.col}>
                                <Text style={pdfStyles.sectionTitle}>Languages</Text>
                                <View style={pdfStyles.skillsRow}>
                                    {languages.map((l, i) => <Text key={i} style={pdfStyles.skillTag}>{l}</Text>)}
                                </View>
                            </View>
                        )}
                    </View>
                </View>
                <View style={pdfStyles.footer}>
                    <Text>Generated by Jobmate • Nepal's First Verified Job Platform</Text>
                </View>
            </Page>
        </Document>
    )
}

export default ResumePDF