const ResumePreview = ({ data }) => {
    const skills = data.skills ? data.skills.split(',').map(s => s.trim()).filter(Boolean) : []
    const languages = data.languages ? data.languages.split(',').map(l => l.trim()).filter(Boolean) : []

    return (
        <div className='bg-white text-gray-900 w-full text-[11px] leading-relaxed font-sans'>
            <div className='bg-green-700 text-white px-6 py-5'>
                <h1 className='text-xl font-bold'>{data.fullName || 'Your Name'}</h1>
                <div className='flex flex-wrap gap-x-4 gap-y-1 mt-2 text-green-100 text-[10px]'>
                    {data.email && <span>✉ {data.email}</span>}
                    {data.phone && <span>📱 {data.phone}</span>}
                    {data.location && <span>📍 {data.location}</span>}
                    {data.linkedin && <span>💼 {data.linkedin}</span>}
                    {data.website && <span>🌐 {data.website}</span>}
                </div>
            </div>
            <div className='px-6 py-4 space-y-4'>
                {data.summary && (
                    <div>
                        <div className='text-[9px] font-bold text-green-700 uppercase tracking-widest border-b border-green-200 pb-1 mb-2'>Professional Summary</div>
                        <p className='text-gray-600'>{data.summary}</p>
                    </div>
                )}
                {data.experience && (
                    <div>
                        <div className='text-[9px] font-bold text-green-700 uppercase tracking-widest border-b border-green-200 pb-1 mb-2'>Work Experience</div>
                        <p className='text-gray-600 whitespace-pre-line'>{data.experience}</p>
                    </div>
                )}
                {data.education && (
                    <div>
                        <div className='text-[9px] font-bold text-green-700 uppercase tracking-widest border-b border-green-200 pb-1 mb-2'>Education</div>
                        <p className='text-gray-600 whitespace-pre-line'>{data.education}</p>
                    </div>
                )}
                {(skills.length > 0 || languages.length > 0) && (
                    <div className='grid grid-cols-2 gap-4'>
                        {skills.length > 0 && (
                            <div>
                                <div className='text-[9px] font-bold text-green-700 uppercase tracking-widest border-b border-green-200 pb-1 mb-2'>Skills</div>
                                <div className='flex flex-wrap gap-1'>
                                    {skills.map((s, i) => (
                                        <span key={i} className='bg-green-50 border border-green-200 text-green-800 px-2 py-0.5 rounded-full text-[9px]'>{s}</span>
                                    ))}
                                </div>
                            </div>
                        )}
                        {languages.length > 0 && (
                            <div>
                                <div className='text-[9px] font-bold text-green-700 uppercase tracking-widest border-b border-green-200 pb-1 mb-2'>Languages</div>
                                <div className='flex flex-wrap gap-1'>
                                    {languages.map((l, i) => (
                                        <span key={i} className='bg-green-50 border border-green-200 text-green-800 px-2 py-0.5 rounded-full text-[9px]'>{l}</span>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>
                )}
                {!data.fullName && !data.experience && !data.skills && (
                    <div className='text-center py-10 text-gray-300'>
                        <div className='text-4xl mb-2'>📄</div>
                        <p className='text-xs'>Fill the form to see live preview</p>
                    </div>
                )}
            </div>
            <div className='text-center text-[8px] text-gray-300 py-2 border-t border-gray-100'>
                Generated by Jobmate • Nepal's First Verified Job Platform
            </div>
        </div>
    )
}

export default ResumePreview